sudo: required
language: generic

services: -docker
before_install:
  - echo "start!!!!!---!!!!!!"
  - docker build -t docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  regine: "us-west-2"
  app: "docker-react-app"
  env: "Dockerreactapp.env"
  bucket_name: "elasticbeanstalk-us-west-2-968478777257"
  backet_path: "elasticbeanstalk-us-west-2-968478777257"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
after_success:
  - echo "test Success !!!!---!!!!!!!"
