sudo: required
language: generic

services: -docker
before_install:
  - echo "start!!!!!---!!!!!!"
  - docker build -t docker-react-app -f Dockerfile.dev

script:
  - docker run -e CI=true docker-react-app npm run test -- --coverage

after_success:
  - echo "test Success !!!!---!!!!"
